---

- name: generate the agent key
  shell: |
    tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 128 | head -n 1
  register: scyllamgr_auth_token
  delegate_to: localhost
  run_once: true

- name: store the auth token in a local file for later use
  copy:
    content: |
      {{ scyllamgr_auth_token.stdout }}
    dest: scyllamgr_auth_token.txt
  delegate_to: localhost
  run_once: true

- name: run scyllamgr_agent_setup
  shell: |
    scyllamgr_agent_setup -y
  become: true

- name: add the auth token to agent configuration
  lineinfile:
    path: /etc/scylla-manager-agent/scylla-manager-agent.yaml
    regexp: '^auth_token:'
    line: 'auth_token: {{ scyllamgr_auth_token.stdout }}'
  become: true

- name: insert additional configuration options for the manager agent
  blockinfile:
    path: /etc/scylla-manager-agent/scylla-manager-agent.yaml
    block: "{{ scylla_manager_agent_config }}"
    insertafter: EOF
  when: scylla_manager_agent_config is defined
  become: true

- name: start and enable the Manager agent service
  service:
    name: scylla-manager-agent
    state: restarted
    enabled: yes
  become: true
