---
- name: Add EPEL key
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
  when: install_type == 'online' and (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")
  become: true

- name: Add EPEL repository
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when: install_type == 'online' and (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")
  become: true

- name: Install ELRepo kernel
  block:
    - name: install ELRepo key
      rpm_key:
        state: present
        key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

    - name: Add ELRepo repository
      yum_repository:
        name: elrepo
        description: ELREPO
        baseurl: https://elrepo.org/linux/kernel/el$releasever/$basearch/

    - name: Install the ELRepo kernel
      yum:
        name: kernel-ml
        state: present
  when: elrepo_kernel == True and install_type == 'online' and (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")
  become: true

- name: remove abrt
  package:
    name: abrt
    state: absent
  become: true

- name: Install Scylla repo
  get_url:
    url: "{{ item }}"
    dest: '/etc/yum.repos.d/{{ item.split("/")[-1] | lower }}'
    mode: '0644'
    owner: root
  with_items: "{{ scylla_repos }}"
  when: item.split(".")[-1] == "repo"
  become: true

- name: Install Scylla
  block:
  - name: Install latest OSS Scylla
    yum:
      name: scylla
      state: latest
    when: scylla_version == 'latest' and scylla_edition == 'oss'

  - name: Install latest Enterprise Scylla
    yum:
      name: scylla-enterprise
      state: latest
    when: scylla_version == 'latest' and scylla_edition == 'enterprise'

  - name: Install specified OSS Scylla
    yum:
      name: "scylla-{{ scylla_version }}"
      state: present
    when: scylla_version != 'latest' and scylla_edition == 'oss'

  - name: Install specified Enterprise Scylla
    yum:
      name: "scylla-enterprise-{{ scylla_version }}"
      state: present
    when: scylla_version != 'latest' and scylla_edition == 'enterprise'
  become: true

- name: install prerequisite python-yaml
  shell: |
    for i in `yum search python3|grep -i pyyaml|awk '{ print $1 }'`; do sudo yum -y install $i; done
  become: true

- name: install and configure Scylla Manager Agent
  block:
    - name: add Scylla Manager repo
      get_url:
        url: "{{ scylla_manager_repo_url }}"
        dest: '/etc/yum.repos.d/{{ scylla_manager_repo_url.split("/")[-1] | lower }}'
        mode: '0644'
        owner: root
      when: scylla_manager_repo_url.split(".")[-1] == "repo"

    - name: install the manager agent
      yum:
        name: scylla-manager-agent
        state: present
  become: true
  when: scylla_manager_enabled|bool == true
