---
- name: read the contents of the auth_token_file
  set_fact:
    auth_token: "{{ lookup('file', item.auth_token_file) }}"

- name: run sctool cluster add for "{{ item.cluster_name }}"
  shell: |
    sctool cluster add \
      --host {{ item.host }} \
      --auth-token "{{ auth_token }}" \
      --name {{ item.cluster_name }} \
      {% if item.without_token is defined and item.without_token|bool == true %}
      --without_token \
      {% endif %}
      {% if item.username is defined and item.password is defined %}
      --username {{ item.username }} \
      --password {{ item.password }} \
      {% endif %}




