---

- name: Add EPEL repository
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when: install_type == 'online' and (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")
  become: true

- name: add scylla-manager repo
  get_url:
    url: "{{ scylla_manager_repo_url }}"
    dest: '/etc/yum.repos.d/{{ scylla_manager_repo_url.split("/")[-1] | lower }}'
    mode: '0644'
    owner: root
  become: true

- name: install manager
  yum:
    name:
      - scylla-manager-server
      - scylla-manager-client
    state: present
  become: true
