---
- name: Rolling restart across a Scylla cluster
  hosts: scylla
  serial: 1
  become: true
  vars:
    # Specify the NIC. The default is the default NIC on the host {{ ansible_default_ipv4.interface }}
    # Alternatively, this can be set to eth0 or any other NIC name, as long as it is similar across the cluster
    scylla_nic: "{{ ansible_default_ipv4.interface }}"

  tasks:
    - name: checking limit arg
      fail:
        msg: "You must use -l or --limit. To restart the entire cluster, use -l 'all'"
      when: ansible_limit is not defined
      run_once: true

    - name: run nodetool drain
      shell: |
        nodetool drain

    - name: wait for DRAIN to complete
      shell: |
        journalctl -u scylla-server --since "1 minute ago" | grep 'storage_service - DRAINED:'
      retries: 300
      delay: 1
      register: drain_result
      until: drain_result.rc == 0

    - name: Restart Scylla service
      service:
        name: scylla-server
        state: restarted

    - name: wait for the cluster to become healthy
      shell: |
        nodetool status|grep -E '^UN|^UJ|^DN'|wc -l
      register: node_count
      until: node_count.stdout|int == ansible_play_batch|length
      retries: 300
      delay: 1
