---

- name: Run cleanup
  hosts: scylla
  gather_facts: false
  serial: 1
  tasks:
    - name: checking limit arg
      fail:
        msg: "You must use -l or --limit. To restart the entire cluster, use -l 'all'"
      when: ansible_limit is not defined

    - name: Run cleanup
      script:  files/repair.sh





